CREATE TABLE users
(
    username   VARCHAR(255) NOT NULL PRIMARY KEY,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
