CREATE TABLE calculator_history (
    id SERIAL PRIMARY KEY,
    expression VARCHAR(255) NOT NULL,
    result DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES users(id)
);